### ISSUE TITLE
Auto add "https://" header on website URLs

### ISSUE THREAD

**Issue by wolfgang-WY** [danielfebrero/bonbon-web-browser#4]
Browser doesn't add "https://" automatically, thus requiring manual input. Looking forward for such feature to be implemented in future

**Comment by danielfebrero** [comment]
Thank you for filling an issue. I will provide a solution asap.

**Comment by danielfebrero** [comment]
https://github.com/danielfebrero/bonbon-web-browser/commit/1ae6da9e075ed694c92deb699b29381556f18ecc

Implementation pushed to master. It will be part of the next release.
